# Proyecto de Clasificación
## Data set por usar: "Mushrooms"

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("mushrooms.csv")
df.head()
# Se observan que las columnas son datos de clasificación así que es un buen data set para analizar

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
# Revisamos la estadística descriptiva de los datos e identificamos nuestra variable objetivo, en este data set es "class"
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [4]:
df.isna().sum(axis=0)
# Se observa que no se encuentran datos faltantes en el data set y se puede empezar a trabajar con ella

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

## Creamos las matrices 'X' y 'y'

In [5]:
# Definimos "X" y "y"
y=df['class']
df=df.drop(columns=['class'])
X=df

((8124, 22), (8124,))

In [6]:
# Normalizamos los datos en "y"
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 0, 0, ..., 0, 1, 0])

In [7]:
# Hacemos lo mismo con "X" ayudandonos con un ciclo for
for i in X:
    X[i] =le.fit_transform(X[i])

/tmp/ipykernel_1014/2331588718.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i] =le.fit_transform(X[i])
/tmp/ipykernel_1014/2331588718.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i] =le.fit_transform(X[i])
/tmp/ipykernel_1014/2331588718.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing

In [8]:
# empezamos a separar nuestras database en entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=7487)

In [9]:
#Seleccionamos el modelo para clasificación
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## Hacemos la búsqueda de los mejores hiperparámetros para ambos modelos.

In [10]:
from sklearn.model_selection import GridSearchCV


In [11]:
parametros1={"criterion": ("gini", "entropy"),
              "n_estimators" : (10, 20, 30), 
              "max_samples" : (1/3, 2/3)}
mejor_modelo1=GridSearchCV(model,parametros1,scoring="accuracy")

In [12]:
# Entrenamos en busca de los mejores parámetros
mejor_modelo1.fit(X_train,y_train)
print(mejor_modelo1.cv_results_["params"])

[{'criterion': 'gini', 'max_samples': 0.3333333333333333, 'n_estimators': 10}, {'criterion': 'gini', 'max_samples': 0.3333333333333333, 'n_estimators': 20}, {'criterion': 'gini', 'max_samples': 0.3333333333333333, 'n_estimators': 30}, {'criterion': 'gini', 'max_samples': 0.6666666666666666, 'n_estimators': 10}, {'criterion': 'gini', 'max_samples': 0.6666666666666666, 'n_estimators': 20}, {'criterion': 'gini', 'max_samples': 0.6666666666666666, 'n_estimators': 30}, {'criterion': 'entropy', 'max_samples': 0.3333333333333333, 'n_estimators': 10}, {'criterion': 'entropy', 'max_samples': 0.3333333333333333, 'n_estimators': 20}, {'criterion': 'entropy', 'max_samples': 0.3333333333333333, 'n_estimators': 30}, {'criterion': 'entropy', 'max_samples': 0.6666666666666666, 'n_estimators': 10}, {'criterion': 'entropy', 'max_samples': 0.6666666666666666, 'n_estimators': 20}, {'criterion': 'entropy', 'max_samples': 0.6666666666666666, 'n_estimators': 30}]


In [13]:
#Mejores parámetros (seleccionados aleatoriamente)
print(mejor_modelo1.best_score_)
print(mejor_modelo1.best_params_)

1.0
{'criterion': 'gini', 'max_samples': 0.3333333333333333, 'n_estimators': 20}


In [14]:
# Hacemos la predicción con el mejor modelo
y_pred=mejor_modelo1.predict(X_test)

In [19]:
# Mandamos a llamar al segundo modelo
from sklearn.naive_bayes import GaussianNB
model2=GaussianNB()
model2.get_params()


{'priors': None, 'var_smoothing': 1e-09}

In [23]:
# Entrenamos el modelo
model2.fit(X_train,y_train)

GaussianNB()

In [25]:
y_pred2=model2.predict(X_test)

array([0, 1, 0, ..., 1, 0, 0])

## Reporte de métricas de ambos modelos

In [26]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [27]:
# Accuracy del primer modelo
accuracy_score(y_test,y_pred)

1.0

In [28]:
# Accuracy del segundo modelo
accuracy_score(y_test,y_pred2)

0.9159146841673503

In [29]:
confusion_matrix(y_test,y_pred)

array([[1253,    0],
       [   0, 1185]])

In [31]:
confusion_matrix(y_test,y_pred2)

array([[1139,  114],
       [  91, 1094]])

In [32]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1253
           1       1.00      1.00      1.00      1185

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438



In [34]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1253
           1       0.91      0.92      0.91      1185

    accuracy                           0.92      2438
   macro avg       0.92      0.92      0.92      2438
weighted avg       0.92      0.92      0.92      2438

